M48
; DRILL file {KiCad 7.0.5} date Fri Dec 15 15:54:57 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-15T15:54:57-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.702
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.988
%
G90
G05
T1
X138.074Y-100.355
X148.234Y-100.355
T2
X143.154Y-100.355
T0
M30
